server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://<token>@github.com/<username>/telco-service-config.git
          searchPaths: '{application}'